### ISSUE TITLE
Issues With Cross-Compiling from x86-64 to x86-32

### ISSUE THREAD

**Issue by sjcappella** [Cr4sh/openreil#15]
Hi. First off, I can't say enough how awesome your work is on this project. Great job! I've been investigating moving some of my tools over from using BAP to OpenREIL and I've encountered a few issues. The first is I'm working on a PIN tracing tool and I'd like to be able to run my x32-bit tools on an x64-bit platform. Since x32-bit binaries need x32-bit PIN tools, I needed to cross compile OpenREIL if I'm working on an x64-bit system. The Makefiles don't seem to respect overloading CFLAGS, C[XX|PP]FLAGS, and LDFLAGS with the '-m32' option (or any other option) when building VEX and Capstone. Manually building these libs and then linking against libopenreil works. But, there is also the issue of building against Python dev for a x32-bit target in an x64-bit environment. After I removed pyopenreil from the build process, I could get everything linking correctly and have a tracing tool working for x32-bit PIN tools and targets running on an x64-bit system. 

I haven't much experience in autotools, otherwise I'd submit a pull-request with a patch and I haven't figured out the Python issue. Just thought I'd make you aware of the issue. Thanks again for you work!

**Comment by Cr4sh** [comment]
Hi, thanks for your feedback. 
I'll check how to fix this issue soon, previously I never tried to do cross-compilation of OpenREIL because usually I'm using separate 32-bit virtual machines to work with 32-bit applications.

**Comment by Cr4sh** [comment]
Hi, I fixed cross compilation issues in the most recent versions of Capstone and OpenREIL (there was minor problems with VEX, Capstone and pyopenreil):
https://github.com/Cr4sh/capstone/commit/deeb83eb09b0a6340b823a91e482ee73d0e9a21c
https://github.com/Cr4sh/openreil/commit/fe7c383d6708e9f28d60753f47e0d796cc7a212d

Now to compile 32-bit build of OpenREIL on 64-bit machine you just have to do:
```
$ sudo apt-get install gcc-multilib g++-multilib python:i386 python-dev:i386 cython:i386
$ CFLAGS=-m32 CXXFLAGS=-m32 ./configure
$ CFLAGS=-m32 CXXFLAGS=-m32 make
```

**Comment by sjcappella** [comment]
Awesome! Thanks for the fix! Now I don't have the build the x32-bit targets manually =)
