### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Cr4sh/openreil#2]
I would like to point out that identifiers like "[`_LIBOPENREIL_H_`](https://github.com/Cr4sh/openreil/blob/b4bb1ee2e3dd16f761238bb72ca0b8e9a865e253/libopenreil/include/libopenreil.h#L2)" and "[`_REIL_TRANSLATOR_H_`](https://github.com/Cr4sh/openreil/blob/7502825b4370621ac0ea14f96b702a8a79e7b722/libopenreil/include/reil_translator.h#L2)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Cr4sh** [comment]
Fixed, thanks for pointing.

**Comment by elfring** [comment]
Are there [some update candidates](https://github.com/Cr4sh/openreil/blob/b13030f035b4ab7c7788c764d51fa1841dc8837e/libasmir/include/jumpbuf.h#L1 "Reconsider the use of some underscores?") left over?

**Comment by Cr4sh** [comment]
Yes, there's a lot of other junk and inconsistences in libasmir sources, planning to do a more proper refactoring bit later.
