### ISSUE TITLE
linker can't find libopenreil functions

### ISSUE THREAD

**Issue by AK1230** [Cr4sh/openreil#3]
I installed openreil on my linux machine and when I try the example C code on my machine i got the following error message. Why the linker said it can't find the functions?
--------------------------------------------------
gcc -Wall -g test.c
test.c: In function ‘arg_print’:
test.c:19:5: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
test.c:19:5: warning: incompatible implicit declaration of built-in function ‘memset’ [enabled by default]
test.c:25:9: warning: zero-length gnu_printf format string [-Wformat-zero-length]
test.c:25:9: warning: zero-length gnu_printf format string [-Wformat-zero-length]
test.c: In function ‘main’:
test.c:91:32: warning: pointer targets in initialization differ in signedness [-Wpointer-sign]
/tmp/ccFoenga.o: In function `translate_inst':
/home/david/lab_reil/test.c:77: undefined reference to `reil_init'
/home/david/lab_reil/test.c:81: undefined reference to `reil_translate'
/home/david/lab_reil/test.c:82: undefined reference to `reil_close'
collect2: ld returned 1 exit status

**Comment by Ge0** [comment]
@AK1230: I haven't installed the lib yet, but I guess you should add the `-lopenreil` flag to your command line, so gcc would link the lib against your test code.

**Comment by Cr4sh** [comment]
@AK1230: Yes, you need to do `make install` and specify `-lopenreil` as @Ge0 said. Also, check (Makefile.am)[https://github.com/Cr4sh/openreil/blob/master/libopenreil/apps/Makefile.am] of test application for libopenreil.

**Comment by AK1230** [comment]
Thank you guys, there might be something wrong with my lib or include path settings, I have installed the openreil lib  /usr/local/lib/libopenreil.a and the include file /usr/local/include/libopenreil.h, and I add the libpath as @Ge0 said, it still doesn't working. I also use "nm libopenreil.a | grep reil_init" and got 00000100 r _ZZ9reil_initE19__PRETTY_FUNCTION__
000001a0 T reil_init,
 and this means the lib function reil_init is there, I just can't link it up. Anyway, the python lib works well, I could use this to move on.

**Comment by Ge0** [comment]
@AK1230 have you tried `ldconfig` to reload the ld cache?
