### ISSUE TITLE
Installing openreil on a disconnected machine fails...

### ISSUE THREAD

**Issue by Ge0** [Cr4sh/openreil#6]
... Unless you fetch the libcapstone manually. It's because the installation script goes to fetch the libcapstone repository on github.com, thus needing an internet connection.

I think that the user should consider installing the libcapstone by himself instead of relying on the openreil installation. What do you think about it?

**Comment by Cr4sh** [comment]
I don't see any problem here, if user wants to install capstone manually by himself -- he can do that: build scenario is trying to download capstone only when `capstone/capstone` folder is not exists.

**Comment by Ge0** [comment]
So, can you tell me how can someone install openreil on a disconnected machine? I cannot manage to do so since capstone's makefile requires an internet connection to fetch some repository...

**Comment by Cr4sh** [comment]
I explained how to do it in my previous comment: copy openreil source code tree into, for example, `~/openreil`, then copy capstone engine source into the `~/openreil/capstone/capstone` and run `make`.
