### ISSUE TITLE
Problems building the Python bindings

### ISSUE THREAD

**Issue by joxeankoret** [Cr4sh/openreil#9]
Hi,

I'm having problems building the Python bindings. I'm getting the following error:

```
g++ -pthread -shared -o ../translator.so translator.o ../../libopenreil/src/libopenreil.a -lpython2.7 -fPIC
/usr/bin/ld: ../../libopenreil/src/libopenreil.a(ir_defs.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
../../libopenreil/src/libopenreil.a: could not read symbols: Bad value
```
Any idea? Thanks in advance!

**Comment by Cr4sh** [comment]
There was a similar issue: https://github.com/Cr4sh/openreil/issues/4
Are you using the most recent version from repository?

**Comment by joxeankoret** [comment]
Yes, I'm using the most recent version from the repository.

**Comment by Cr4sh** [comment]
Fixed. It was issue with the new VEX version, you need to update your `VEX/Makefile`.
